version: '3.7'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nw
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - nw
networks:
  nw: