version: '2.1'

services:

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - CONFIG_SERVER_URL=http://configuration-server:5000
      - DISCOVERY_SERVER_URL=http://discovery-server:5102/eureka
      - PORT=5102
    ports:
      - "8761:8761"
      - "5102:5102"
    networks:
      - nw
    healthcheck:
      test: curl -v --silent http://discovery-server:5102/actuator/health/discoveryComposite/eureka 2>&1 | grep UP
      interval: 10s
      retries: 30
      timeout: 5s

  configuration-server:
    build:
      context: ./configuration-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DISCOVERY_SERVER_URL=http://discovery-server:5102/eureka
      - PORT=5000
    restart: always
    networks:
      - nw
    healthcheck:
      test: curl -v --silent http://configuration-server:5000/actuator/health/discoveryComposite/eureka 2>&1 | grep UP
      interval: 10s
      retries: 30
      timeout: 5s
    depends_on:
      discovery-server:
        condition: service_healthy

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7110:7110
    networks:
      - nw
    environment:
      - CONFIG_SERVER_URL=http://configuration-server:5000
      - DISCOVERY_SERVER_URL=http://discovery-server:5102/eureka
      - PORT=7110
    depends_on:
      configuration-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: curl -v --silent http://app:7110/actuator/health/discoveryComposite/eureka 2>&1 | grep UP
      interval: 10s
      retries: 30
      timeout: 5s

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile

    restart: always
    ports:
      - 5200:5200
    networks:
      - nw
    environment:
      - CONFIG_SERVER_URL=http://configuration-server:5000
      - DISCOVERY_SERVER_URL=http://discovery-server:5102/eureka
      - PORT=5200
    healthcheck:
      test: curl -v --silent http://gateway-server:5200/actuator/health/discoveryComposite/eureka 2>&1 | grep UP
      interval: 10s
      retries: 30
      timeout: 5s
    depends_on:
      configuration-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      app:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nw

networks:
  nw: