spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.kdqth.mongodb.net/cluster0?retryWrites=true&w=majority
logging:
  level:
    ROOT: INFO
  file:
    name: library.log
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
mongock:
  change-logs-scan-package:
    - com.valeev.hestia.config.migration
springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
    swagger:
      v2:
        use-model-v3: false
server:
  servlet:
    context-path: /api
app:
  jwtSecret: myBestOfTheBestSecretKey
  jwtExpiration: 86400