spring:
  application:
    name: configuration-server
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5102/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 30
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG