eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL}
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 30
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    backend:
      path: /api/**
logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace
ribbon:
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000000