eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL}
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 15000
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 30
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
zuul:
  routes:
    backend:
      path: /api/**
logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace